[app]
app_name = "Ginthon"
app_version = "1.0.0"
app_class = "ginthon_"
author = "fyonecon"
github = "https://github.com/fyonecon/Ginthon"
docs = "http://datathink.top/#route=ginthon&ap="

[sys]
log_path = "storage/log/" # /结尾
debug = false # true false

[flask]
port = 9100 # 9100
debug = false # true false

[pywebview]
ssl = false
debug = false # true false

[mysql1]
ipv4 = "127.0.0.1:3306" # ip:port
db_name = "test_db"
db_user = "root2"
db_pwd = ""